language: python
python:
- '3.8'
install:
- make install
- pip install -r requirements_test.txt
before_script:
- make verify-lint
script:
- make test
deploy:
  provider: pypi
  username: __token__
  password:
    secure: $PYPI_SECRET
  on:
    tags: true
    branch: master
