name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**.py"
      - ".github/**"
      - "pyproject.toml"
      - "requirements*"

defaults:
  run:
    shell: bash

jobs:
  Pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.12]
        include:
          - os: windows-latest
            python-version: 3.12
          - os: macos-latest
            python-version: 3.12
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-tests.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install rocketpy
        run: pip install .
        continue-on-error: true

      - name: Test importing rocketpy
        run: python -c "import sys, rocketpy; print(f'{rocketpy.__name__} running on Python {sys.version}')"
        continue-on-error: true

      - name: Install test dependencies
        run: pip install -r requirements-tests.txt
        continue-on-error: true

      - name: Run Unit Tests
        run: pytest tests/unit --cov=rocketpy
        continue-on-error: true

      - name: Run Integration Tests
        run: pytest $(find tests -maxdepth 1 -name "*.py") --cov=rocketpy --cov-append
        continue-on-error: true

      - name: Run Documentation Tests
        run: pytest rocketpy --doctest-modules --cov=rocketpy --cov-append
        continue-on-error: true

      - name: Run Acceptance Tests
        run: pytest tests/acceptance --cov=rocketpy --cov-append --cov-report=xml
        continue-on-error: true

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
        continue-on-error: true

  CodecovUpload:
    needs: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all coverage reports
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage.xml
