name: PyTest

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.8
          - 3.11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build RocketPy (without optional dependencies)
        run: |
          pip install .
      - name: Import rocketpy in python and test if it works
        run: |
          python -c "import sys, rocketpy; print(f'{rocketpy.__name__} running on Python {sys.version}')"
      - name: Install optional dependencies
        run: |
          pip install -r requirements-tests.txt
      - name: Test with pytest
        run: |
          pytest
          cd rocketpy
          pytest --doctest-modules
